### ISSUE TITLE
결과창에서 BackgroundTop 이 스크롤 영역을 덮는 현상 제보합니다.

### ISSUE THREAD

**Issue by kor-Chipmunk** [mash-up-kr/MSG#48]
## 개요

결과창에서 윗 영역이 결과창의 스크롤 영역을 덮는 현상이 일어납니다.

OS : macOS 14.2.1 Sonoma
브라우저 : Chrome 121.0.6167.85 ARM

## 스크린샷

![스크린샷 2024-02-09 오후 7 12 32](https://github.com/mash-up-kr/MSG/assets/16275188/6dd0939e-58bd-4b2b-b33c-fa26b0628e7b)

## 코드 해본 것

```tsx
// src/components/result/ResultLayout/ResultLayout.component.tsx

import { PropsWithChildren } from 'react';
import * as Styled from './ResultLayout.styled';

const ResultLayout = ({ children }: PropsWithChildren) => {
  return (
    <Styled.ResultLayout>
      <Styled.BackgroundTop />
      {children}
    </Styled.ResultLayout>
  );
};

export default ResultLayout;
```

에서 BackgroundTop 을 뺍니다.

```tsx
import { PropsWithChildren } from 'react';
import * as Styled from './ResultLayout.styled';

const ResultLayout = ({ children }: PropsWithChildren) => {
  return (
    <Styled.ResultLayout>
      {children}
    </Styled.ResultLayout>
  );
};

export default ResultLayout;
```

![스크린샷 2024-02-09 오후 7 14 44](https://github.com/mash-up-kr/MSG/assets/16275188/55747c28-6948-4c74-9659-f4baaa0777e8)

**Comment by HaJunRyu** [comment]
@kor-Chipmunk 제안해주신 방법 + 스크롤 UI 자체를 제거했습니다. [Deploy Preview 링크](https://deploy-preview-49--dev-recruit-event.netlify.app/)인데 해당 증상이 사라졌는지 확인해주실 수 있나요?

**Comment by HaJunRyu** [comment]
#49 에서 해결되어서 [배포까지 완료](https://recruit-event.mash-up.kr/)됐습니다. 이슈 종료하겠습니다🙇🏻‍♂️
